encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:title>", views.get_title, name="title"),
    path("search", views.search, name="search"),
    path("add", views.add_page, name="add"),
    path("edit/<str:title>", views.edit_page, name="edit"),
    path("random", views.random_page, name="random")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from . import util
import markdown2
from markdown2 import Markdown
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse


class NewPageForm(forms.Form):
    page_title = forms.CharField(
        label="Title",
        widget=forms.TextInput(
            attrs={
                'class':'form-control',
                'placeholder': 'Inform your title page'
            }))
    page_content = forms.CharField(label="Page Content",
    widget=forms.Textarea(
        attrs={
            'style':'resize: none;',
            'class':'form-control',
            "placeholder": "Write your page content"
        }))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "h1_title": "All Pages"
    })

def get_title(request, title):
    entries = util.list_entries()
    md = Markdown()
    if title in entries:
        title_body = util.get_entry(title)
        body_text = md.convert(title_body)

        return render(request, "encyclopedia/title.html", {
            "title": title,
            "body": body_text
        })
    return render(request, "encyclopedia/error.html", {
        "error_message": "There is no page with this title"
    })


def search(request):
    entries = util.list_entries()
    md = Markdown()
    title = request.GET["q"]
    if title in entries:
        title_body = util.get_entry(title)
        return render(request, "encyclopedia/title.html", {
            "title": title,
            "body": md.convert(title_body)
        })
    else:
        possible_entries = [entry for entry in entries if title.lower() in entry.lower()]
        if possible_entries:
            return render(request, "encyclopedia/index.html", {
                "entries": possible_entries,
                "h1_title": "Possible pages"
            })
        else:
            return render(request, "encyclopedia/error.html", {
                "error_message": "There is no page for your request"
            })

def add_page(request):
    if request.method == "POST":
        form = NewPageForm(request.POST)
        if form.is_valid():
            page_t = form.cleaned_data["page_title"]
            page_c = form.cleaned_data["page_content"]
            entries = util.list_entries()
            if page_t in entries:
                return render(request, "encyclopedia/error.html", {
                    "error_message": "entry already exists"
                })
            else:
                util.save_entry(page_t, page_c)
                title = page_t
                title_body = util.get_entry(title)
                md = Markdown()
                return render(request, "encyclopedia/title.html", {
                    "title": title,
                    "body": md.convert(title_body)
                })
        else:
            return render(request, "encyclopedia/newpage.html", {
                "form": form
            })
    return render(request, "encyclopedia/newpage.html",{
        "form": NewPageForm()
    })


def edit_page(request, title):
    if request.method == "POST":
        form = NewPageForm(request.POST)

        if form.is_valid():
            page_t = form.cleaned_data["page_title"]
            page_c = form.cleaned_data["page_content"]
            util.save_entry(page_t, page_c)
            title_body = util.get_entry(title)
            md = Markdown()
            return render(request, "encyclopedia/title.html", {
                "title": title,
                "body": md.convert(title_body)
            })            
    else:
        entry_data = util.get_entry(title)
        form_data = {
            "page_title": title,
            "page_content": entry_data
        }
        form = NewPageForm(
            request.POST or None,
            initial=form_data
        )        
        return render(request, "encyclopedia/editpage.html", {
            "title": title,
            "form": form
        })

def random_page(request):
    title = util.get_random_entry()
    return HttpResponseRedirect(reverse("encyclopedia:title", args=(title,)))
    

encyclopedia/templates/encyclopedia/editpage.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}
                {{ title }}
             {% endblock %}
        </title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div>
            <nav class="navbar navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'encyclopedia:index' %}">Home</a>
            </nav>
        </div>
        <div class="form-group main col-lg-10 col-md-9" >
            <form action="{% url 'encyclopedia:edit' title %}" method="POST">
                {% csrf_token %}
                {{ form.page_title.label }}
                {{ form.page_title }} <br>
                {{ form.page_content.label }}<br>
                {{ form.page_content }}<br>
                <input type="submit" class="btn btn-primary"> 
            </form>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/error.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Error</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <div>
            <nav class="navbar navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'encyclopedia:index' %}">Home</a>
            </nav>
        </div>
        <div class="alert alert-warning" role="alert">
            {{ error_message }}
        </div>
        
    </body>
</html>

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>{{ h1_title }}</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:add' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/newpage.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>     
        <div>
            <nav class="navbar navbar-dark bg-dark">
                <a class="navbar-brand" href="{% url 'encyclopedia:index' %}">Home</a>
            </nav>
        </div>
        <div class="form-group main col-lg-10 col-md-9" >
            <form action="{% url 'encyclopedia:add' %}" method="POST">
                {% csrf_token %}
                {{ form.page_title.label }}
                {{ form.page_title }} <br>
                {{ form.page_content.label }}<br>
                {{ form.page_content }}<br>
                <input type="submit" class="btn btn-primary"> 
            </form>
        </div>
    </body>
</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>List of possible entries</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'encyclopedia:title' entry %}">{{ entry }}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/title.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}
    
{% block body %}
    {{ body|safe }}
    <form action="{% url 'encyclopedia:edit' title %}">
        {% csrf_token %}
        <button type="submit" class="btn btn-secondary">Edit</button>
    </form>
{% endblock %}